# Generated by Django 3.0.5 on 2020-08-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_part_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Genre',
        ),
    ]
