# Generated by Django 3.0.5 on 2020-08-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_part_2', '0003_auto_20200825_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.DateField(verbose_name='Год выпуска'),
        ),
    ]
