# Generated by Django 3.0.5 on 2020-08-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_part_2', '0005_auto_20200825_0954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
