# Generated by Django 3.0.5 on 2020-08-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_part_2', '0006_auto_20200825_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
