# Generated by Django 3.0.5 on 2020-08-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_part_2', '0007_auto_20200825_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(max_length=4, verbose_name='Год выпуска'),
        ),
    ]
