# Generated by Django 3.0.5 on 2020-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_part_2', '0009_auto_20200825_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
