# Generated by Django 3.0.5 on 2020-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_part_2', '0010_auto_20200825_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
