# Generated by Django 3.0.5 on 2020-08-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_part_2', '0011_auto_20200825_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_part_2.Genre'),
        ),
    ]
